# Generated by Django 3.1.11 on 2021-07-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='calification',
            new_name='calificacion',
        ),
        migrations.RenameField(
            model_name='destino',
            old_name='users',
            new_name='usuarios',
        ),
    ]
