# Generated by Django 3.1.11 on 2021-07-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_auto_20210730_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='calificacion',
            field=models.FloatField(default=0),
        ),
    ]
